# 配置文件名稱需符合 application-{profile}.yml 格式
# 啟動時可以用指令來設定要用什麼配置檔
# java -jar spring-boot-demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev

spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: springboot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

book:
  name: 書名
  author: 作者名
  isbn: ${random.uuid}
  description: ${book.name} 描述