#server:
#  port: 8081
#  servlet:
#    context-path: /setting
logging:
  level:
    root: WARN
    com:
      teddy: DEBUG
  file:
    name: logs/my.log

book:
  name: 書名
  author: 作者名
  isbn: ${random.uuid}
  description: ${book.name} 描述